In [1]:
print('Hello World!')

# 自动导入 py文件的变动
%load_ext autoreload
%autoreload 2

Hello World!

In [2]:
from dataloader import InstanceInput

instance_input = InstanceInput('../Data/Instanzen/Instance7_2_1.json')

In [3]:
print(instance_input)

Szenario Flexi
-------------------
Instance ID: 7_2_1
Cohorts: 7
Days: 2
Max Route Duration: 21600

In [5]:
instance_input_operative = InstanceInput('../Data/Instanzen/Instance7_2_1.json', True)
print(instance_input_operative)

Szenario Operative
-------------------
Instance ID: 7_2_1
Cohorts: 7
Days: 2
Max Route Duration: 21600
14 tasks loaded
Use Main Task: True

In [6]:
print(instance_input_operative.MainTasks)

[{'ID': 'MT-FWI-1', 'Day': 2, 'ServiceTime': 6300, 'StartTime': 9000, 'EndTime': 15300, 'LocationID': 747, 'Latitude': 51.0675509, 'Longitude': 13.7764159}, {'ID': 'MT-FWI-2', 'Day': 1, 'ServiceTime': 4500, 'StartTime': 5400, 'EndTime': 9900, 'LocationID': 44, 'Latitude': 51.0507815, 'Longitude': 13.724789}, {'ID': 'MT-FWI-3', 'Day': 1, 'ServiceTime': 5400, 'StartTime': 11700, 'EndTime': 17100, 'LocationID': 142, 'Latitude': 51.0686787, 'Longitude': 13.7863437}, {'ID': 'MT-FWI-4', 'Day': 2, 'ServiceTime': 6300, 'StartTime': 7200, 'EndTime': 13500, 'LocationID': 328, 'Latitude': 51.0270898, 'Longitude': 13.8285576}, {'ID': 'MT-FWI-5', 'Day': 2, 'ServiceTime': 5400, 'StartTime': 5400, 'EndTime': 10800, 'LocationID': 886, 'Latitude': 51.0496329, 'Longitude': 13.6542996}, {'ID': 'MT-FWI-6', 'Day': 1, 'ServiceTime': 6300, 'StartTime': 3600, 'EndTime': 9900, 'LocationID': 771, 'Latitude': 51.0309756, 'Longitude': 13.7908851}, {'ID': 'MT-FWI-7', 'Day': 1, 'ServiceTime': 5400, 'StartTime': 8100, 'EndTime': 13500, 'LocationID': 855, 'Latitude': 51.082625, 'Longitude': 13.7591178882}, {'ID': 'MT-FWI-8', 'Day': 2, 'ServiceTime': 3600, 'StartTime': 13500, 'EndTime': 17100, 'LocationID': 813, 'Latitude': 51.0277882, 'Longitude': 13.7601536}, {'ID': 'MT-FWI-9', 'Day': 1, 'ServiceTime': 4500, 'StartTime': 7200, 'EndTime': 11700, 'LocationID': 218, 'Latitude': 51.0210547, 'Longitude': 13.7158879}, {'ID': 'MT-FWI-10', 'Day': 1, 'ServiceTime': 5400, 'StartTime': 9000, 'EndTime': 14400, 'LocationID': 857, 'Latitude': 51.0046365, 'Longitude': 13.8406999}, {'ID': 'MT-FWI-11', 'Day': 2, 'ServiceTime': 4500, 'StartTime': 5400, 'EndTime': 9900, 'LocationID': 828, 'Latitude': 51.0479853, 'Longitude': 13.7321184}, {'ID': 'MT-FWI-12', 'Day': 1, 'ServiceTime': 5400, 'StartTime': 8100, 'EndTime': 13500, 'LocationID': 878, 'Latitude': 50.99135, 'Longitude': 13.7894941}, {'ID': 'MT-FWI-13', 'Day': 2, 'ServiceTime': 7200, 'StartTime': 9000, 'EndTime': 16200, 'LocationID': 727, 'Latitude': 51.0495393, 'Longitude': 13.7075854}, {'ID': 'MT-FWI-14', 'Day': 2, 'ServiceTime': 5400, 'StartTime': 7200, 'EndTime': 12600, 'LocationID': 235, 'Latitude': 51.0402257, 'Longitude': 13.7170067}]

In [7]:
instance_input_operative.get_main_tasks_df() # * main tasks, subtasks, 效果不错, 不需要额外清洗

           ID  Day  ServiceTime  ...  LocationID   Latitude  Longitude
0    MT-FWI-1    2         6300  ...         747  51.067551  13.776416
1    MT-FWI-2    1         4500  ...          44  51.050781  13.724789
2    MT-FWI-3    1         5400  ...         142  51.068679  13.786344
3    MT-FWI-4    2         6300  ...         328  51.027090  13.828558
4    MT-FWI-5    2         5400  ...         886  51.049633  13.654300
5    MT-FWI-6    1         6300  ...         771  51.030976  13.790885
6    MT-FWI-7    1         5400  ...         855  51.082625  13.759118
7    MT-FWI-8    2         3600  ...         813  51.027788  13.760154
8    MT-FWI-9    1         4500  ...         218  51.021055  13.715888
9   MT-FWI-10    1         5400  ...         857  51.004636  13.840700
10  MT-FWI-11    2         4500  ...         828  51.047985  13.732118
11  MT-FWI-12    1         5400  ...         878  50.991350  13.789494
12  MT-FWI-13    2         7200  ...         727  51.049539  13.707585
13  MT-FWI-14    2         5400  ...         235  51.040226  13.717007

[14 rows x 8 columns]

In [10]:
from dataloader import OptionalTasksInput
option_task = OptionalTasksInput('../Data/OptionalTasks.csv')
option_task.get_dataframe()

                 ID                    Street  ... ServiceTime Profit
0     PE-FWI-5-5985              Fabrikstraße  ...           0      0
1     PE-FWI-3-5292            Bulgakowstraße  ...         780      1
2     PE-FWI-3-4048        Fritz-Busch-Straße  ...         840      1
3     PE-FWI-2-7618        Julie-Salinger-Weg  ...        1020      2
4     PE-FWI-3-2483             Löscherstraße  ...         840      1
...             ...                       ...  ...         ...    ...
996   PE-FWI-1-1229      Weesensteiner Straße  ...        1560      3
997   PE-FWI-4-4983              Polierstraße  ...         780      3
998   PE-FWI-4-9316               Bürgerwiese  ...         900      3
999   PE-FWI-3-4469  Arno-Schellenberg-Straße  ...         720      1
1000  PE-FWI-3-5647        Pirnaer Landstraße  ...         900      1

[1001 rows x 11 columns]